[package]
name = "countdownlatch"
version = "0.1.0"
authors = ["wolf4ood <enrico.risa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]


[dev-dependencies]
futures-executor = "0.3.4"
futures-util = "0.3.4"
async-std = { version = "1.5.0", features = ["attributes"] }

[features]
multi = []


[[example]]
name = "async_std_multi"
required-features = ["multi"]